spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
mybatis:
  mapper-locations: classpath:mapper/*.xml®
